'use client';

import { Download, Copy, FileText, Share2, Mail, Check, FileArchive, Globe } from 'lucide-react';
import type { CampaignOutput, CampaignWorkflow } from '@/app/types';

interface ExportPanelProps {
  workflow: CampaignWorkflow | null;
}

export function ExportPanel({ workflow }: ExportPanelProps) {
  const campaign = workflow?.campaign;

  const copyToClipboard = async (text: string, label: string) => {
    try {
      await navigator.clipboard.writeText(text);
      alert(`${label} copied to clipboard!`);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  // Download as styled HTML
  const downloadHTML = () => {
    if (!campaign || !workflow) return;
    const title = workflow.sourceDocument.title || 'Campaign Kit';
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title} — Campaign Kit</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; background: #f8fafc; color: #1e293b; line-height: 1.7; }
    .container { max-width: 800px; margin: 0 auto; padding: 40px 24px; }
    .header { text-align: center; margin-bottom: 48px; padding-bottom: 32px; border-bottom: 2px solid #e2e8f0; }
    .header h1 { font-size: 28px; font-weight: 800; color: #0f172a; margin-bottom: 8px; }
    .header .meta { font-size: 13px; color: #94a3b8; }
    .section { margin-bottom: 40px; background: #fff; border-radius: 12px; padding: 32px; box-shadow: 0 1px 3px rgba(0,0,0,0.06); border: 1px solid #e2e8f0; }
    .section-header { display: flex; align-items: center; gap: 10px; margin-bottom: 20px; padding-bottom: 12px; border-bottom: 1px solid #f1f5f9; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; }
    .badge-blog { background: #dbeafe; color: #1d4ed8; }
    .badge-social { background: #dcfce7; color: #15803d; }
    .badge-email { background: #fef3c7; color: #b45309; }
    .section h2 { font-size: 20px; font-weight: 700; color: #0f172a; }
    .section .tone { font-size: 12px; color: #94a3b8; margin-top: 2px; }
    .content { font-size: 15px; color: #334155; white-space: pre-wrap; }
    .footer { text-align: center; margin-top: 48px; padding-top: 24px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; }
    @media print { body { background: #fff; } .section { box-shadow: none; break-inside: avoid; } }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📦 ${title}</h1>
      <p class="meta">Campaign Kit · Generated ${date}</p>
    </div>

    <div class="section">
      <div class="section-header">
        <span class="badge badge-blog">Blog Post</span>
        <h2>Blog Post</h2>
      </div>
      <p class="tone">Tone: ${campaign.blogPost.tone} · Status: ${campaign.blogPost.status}</p>
      <div class="content">${escapeHtml(campaign.blogPost.content)}</div>
    </div>

    <div class="section">
      <div class="section-header">
        <span class="badge badge-social">Social Thread</span>
        <h2>Social Media Thread</h2>
      </div>
      <p class="tone">Tone: ${campaign.socialThread.tone} · Status: ${campaign.socialThread.status}</p>
      <div class="content">${escapeHtml(campaign.socialThread.content)}</div>
    </div>

    <div class="section">
      <div class="section-header">
        <span class="badge badge-email">Email Teaser</span>
        <h2>Email Teaser</h2>
      </div>
      <p class="tone">Tone: ${campaign.emailTeaser.tone} · Status: ${campaign.emailTeaser.status}</p>
      <div class="content">${escapeHtml(campaign.emailTeaser.content)}</div>
    </div>

    <div class="footer">
      <p>Generated by Autonomous Content Factory · ${date}</p>
    </div>
  </div>
</body>
</html>`;

    downloadFile(html, `campaign-${workflow.id.slice(0, 8)}.html`, 'text/html');
  };

  // Download as ZIP with separate files
  const downloadZIP = async () => {
    if (!campaign || !workflow) return;

    const JSZip = (await import('jszip')).default;
    const zip = new JSZip();
    const title = workflow.sourceDocument.title || 'Campaign';
    const folder = zip.folder(`${title} - Campaign Kit`)!;

    folder.file('blog-post.txt', campaign.blogPost.content);
    folder.file('social-thread.txt', campaign.socialThread.content);
    folder.file('email-teaser.txt', campaign.emailTeaser.content);
    folder.file('README.txt',
      `Campaign Kit: ${title}\n` +
      `Generated: ${new Date().toLocaleString()}\n\n` +
      `Files:\n` +
      `  blog-post.txt     — Blog Post (Tone: ${campaign.blogPost.tone})\n` +
      `  social-thread.txt — Social Media Thread (Tone: ${campaign.socialThread.tone})\n` +
      `  email-teaser.txt  — Email Teaser (Tone: ${campaign.emailTeaser.tone})\n`
    );

    const blob = await zip.generateAsync({ type: 'blob' });
    downloadFile(blob, `campaign-${workflow.id.slice(0, 8)}.zip`, 'application/zip');
  };

  const allApproved = campaign?.blogPost.status === 'approved' &&
                       campaign?.socialThread.status === 'approved' &&
                       campaign?.emailTeaser.status === 'approved';

  return (
    <div className="space-y-8">
      <div className="flex items-center gap-3 border-b border-gray-200/50 dark:border-gray-800/50 pb-4">
        <div className="p-2 rounded-lg bg-purple-50 dark:bg-purple-900/20 text-purple-600 dark:text-purple-400">
          <Download className="w-5 h-5" />
        </div>
        <h2 className="text-xl font-bold text-gray-900 dark:text-white tracking-tight">
          Export Center
        </h2>
      </div>

      <div className="space-y-4">
        {/* Download Buttons */}
        <div className="grid grid-cols-2 gap-3">
          <button
            onClick={downloadHTML}
            disabled={!campaign}
            aria-label="Download campaign as styled HTML"
            className={`flex items-center justify-center gap-2 px-5 py-4 rounded-xl font-bold text-sm transition-all ${
              campaign
                ? 'bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white hover:-translate-y-0.5 shadow-lg shadow-blue-500/20'
                : 'bg-gray-200 text-gray-400 cursor-not-allowed opacity-50'
            }`}
          >
            <Globe className="w-5 h-5" />
            Download HTML
          </button>
          <button
            onClick={downloadZIP}
            disabled={!campaign}
            aria-label="Download campaign as ZIP archive"
            className={`flex items-center justify-center gap-2 px-5 py-4 rounded-xl font-bold text-sm transition-all ${
              campaign
                ? 'bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white hover:-translate-y-0.5 shadow-lg shadow-emerald-500/20'
                : 'bg-gray-200 text-gray-400 cursor-not-allowed opacity-50'
            }`}
          >
            <FileArchive className="w-5 h-5" />
            Download ZIP
          </button>
        </div>

        {/* Individual Preview Buttons */}
        {campaign && (
          <div className="grid grid-cols-3 gap-2">
            <button
              onClick={() => window.open(`/preview/blog/${workflow.id}`, '_blank')}
              aria-label="Preview blog post in a new tab"
              className="flex flex-col items-center gap-1.5 p-4 rounded-xl border border-gray-200 dark:border-gray-700 hover:bg-blue-50 dark:hover:bg-blue-900/20 hover:border-blue-200 dark:hover:border-blue-800 transition-all group"
            >
              <FileText className="w-6 h-6 text-blue-600 dark:text-blue-400 group-hover:scale-110 transition-transform" />
              <span className="text-xs font-bold text-gray-700 dark:text-gray-300">Preview Blog</span>
            </button>
            <button
              onClick={() => window.open(`/preview/social/${workflow.id}`, '_blank')}
              aria-label="Preview social media thread in a new tab"
              className="flex flex-col items-center gap-1.5 p-4 rounded-xl border border-gray-200 dark:border-gray-700 hover:bg-green-50 dark:hover:bg-green-900/20 hover:border-green-200 dark:hover:border-green-800 transition-all group"
            >
              <Share2 className="w-6 h-6 text-green-600 dark:text-green-400 group-hover:scale-110 transition-transform" />
              <span className="text-xs font-bold text-gray-700 dark:text-gray-300">Preview Social</span>
            </button>
            <button
              onClick={() => window.open(`/preview/email/${workflow.id}`, '_blank')}
              className="flex flex-col items-center gap-1.5 p-4 rounded-xl border border-gray-200 dark:border-gray-700 hover:bg-amber-50 dark:hover:bg-amber-900/20 hover:border-amber-200 dark:hover:border-amber-800 transition-all group"
            >
              <Mail className="w-6 h-6 text-amber-600 dark:text-amber-400 group-hover:scale-110 transition-transform" />
              <span className="text-xs font-bold text-gray-700 dark:text-gray-300">Preview Email</span>
            </button>
          </div>
        )}

        {/* Status Summary */}
        {campaign && (
          <div className="p-3 rounded-lg bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700">
            <div className="flex items-center gap-2 mb-2">
              <Check className={`w-4 h-4 ${allApproved ? 'text-green-500' : 'text-gray-400'}`} />
              <span className="text-sm font-medium">
                {allApproved ? 'All content approved' : 'Content in review'}
              </span>
            </div>
            <div className="text-xs text-gray-500 space-y-1">
              <p>Blog: {campaign.blogPost.status}</p>
              <p>Social: {campaign.socialThread.status}</p>
              <p>Email: {campaign.emailTeaser.status}</p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// Helpers
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function downloadFile(content: Blob | string, filename: string, type: string) {
  const blob = content instanceof Blob ? content : new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
